import React, { useState } from 'react';
import { useAppStore } from '../store/useAppStore';
import { checkTransferCode, useTransferCode } from '../services/customerService';
import toast from 'react-hot-toast';

const InitiateTransfer: React.FC = () => {
  const { customer } = useAppStore();
  const [step, setStep] = useState(1);
  const [loading, setLoading] = useState(false);

  // Step 1
  const [codeId, setCodeId] = useState('');
  const [validatedCode, setValidatedCode] = useState<any>(null);

  // Transfer Fields (once code validated)
  const [toAccount, setToAccount] = useState('');
  const [amount, setAmount] = useState('');
  const [narration, setNarration] = useState('');

  const handleValidateCode = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!customer?.id) return;
    setLoading(true);
    try {
      const code = await checkTransferCode(customer.id, codeId);
      if (!code || code.status !== 'ACTIVE') {
        throw new Error('Code is inactive or invalid');
      }
      setValidatedCode(code);
      toast.success('Code Validated');
      setStep(2);
    } catch (err: any) {
      toast.error(err.message || 'Validation failed');
    } finally {
      setLoading(false);
    }
  };

  const handleConfirm = () => {
    if (!amount) return;
    setStep(3);
  };

  const handleExecute = async () => {
    if (!customer?.id || !validatedCode) return;
    setLoading(true);
    try {
      const txn = await useTransferCode(
        customer.id,
        validatedCode.id,
        toAccount,
        parseFloat(amount),
        narration
      );
      toast.success('Transfer initiated successfully!');
      setStep(4);
    } catch (err: any) {
      toast.error(err.message || 'Transfer failed');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
      <div className="px-6 py-4 border-b border-gray-200 bg-gray-50 flex justify-between items-center">
        <h3 className="text-lg font-bold text-gray-800">Secure Transfer System</h3>
        <span className="text-xs text-gray-500 font-bold uppercase tracking-wider">Step {step} of 3</span>
      </div>

      <div className="p-6">
        {step === 1 && (
          <form onSubmit={handleValidateCode} className="space-y-4 max-w-md">
            <h4 className="font-semibold text-gray-700">Enter Transfer Code</h4>
            <p className="text-xs text-gray-500">Provide the secure UUID transfer authorization code generated by the institution.</p>
            <input
              required
              placeholder="Code ID (UUID)"
              value={codeId}
              onChange={(e) => setCodeId(e.target.value)}
              className="w-full p-2.5 border rounded-lg focus:ring-2 focus:ring-red-500 focus:outline-none"
            />
            <button disabled={loading} type="submit" className="w-full py-2 bg-red-600 hover:bg-red-700 text-white rounded font-medium transition">
              {loading ? 'Validating...' : 'Validate Code'}
            </button>
          </form>
        )}

        {step === 2 && (
          <div className="space-y-4 max-w-md">
            <h4 className="font-semibold text-gray-700 font-bold">Transfer Specifications</h4>
            <div className="grid grid-cols-2 gap-2 text-sm bg-gray-50 p-3 rounded">
              <span className="text-gray-500">COT Code Enabled:</span>
              <span className="font-bold">{validatedCode?.cot_code ? 'Yes' : 'No'}</span>
              <span className="text-gray-500">Tax Code Enabled:</span>
              <span className="font-bold">{validatedCode?.tax_code ? 'Yes' : 'No'}</span>
            </div>

            <input
              required
              placeholder="To Account Number"
              value={toAccount}
              onChange={(e) => setToAccount(e.target.value)}
              className="w-full p-2.5 border rounded-lg"
            />
            <input
              required
              type="number"
              placeholder="Amount ($)"
              value={amount}
              onChange={(e) => setAmount(e.target.value)}
              className="w-full p-2.5 border rounded-lg"
            />
            <input
              required
              placeholder="Narration"
              value={narration}
              onChange={(e) => setNarration(e.target.value)}
              className="w-full p-2.5 border rounded-lg"
            />

            <button onClick={handleConfirm} className="w-full py-2 bg-red-600 hover:bg-red-700 text-white rounded font-medium transition">
              Continue to Confirmation
            </button>
          </div>
        )}

        {step === 3 && (
          <div className="space-y-4 max-w-md">
            <h4 className="font-semibold text-gray-700">Confirm Compliance Details</h4>
            <div className="p-4 border rounded bg-gray-50 space-y-2 text-sm">
              <p><strong>To Account:</strong> {toAccount}</p>
              <p><strong>Transfer Amount:</strong> ${parseFloat(amount).toLocaleString()}</p>
              <p><strong>Narration:</strong> {narration}</p>
            </div>
            <p className="text-xs text-gray-500">By continuing, you authorize compliance checks on COT, Tax, and IRS codes sequence validations.</p>
            <div className="flex gap-2">
              <button onClick={() => setStep(2)} className="flex-1 py-2 bg-gray-200 text-gray-700 rounded font-medium">Back</button>
              <button disabled={loading} onClick={handleExecute} className="flex-1 py-2 bg-red-600 hover:bg-red-700 text-white rounded font-medium transition">
                {loading ? 'Processing...' : 'Authorize Transfer'}
              </button>
            </div>
          </div>
        )}

        {step === 4 && (
          <div className="space-y-4 max-w-md text-center">
            <h4 className="text-xl font-bold text-green-600">Compliance Hold Active</h4>
            <p className="text-sm text-gray-600">The transfer was logged successfully. Compliance locks COT, Tax, and IRS approvals must be validated by the administrators.</p>
            <button
              onClick={() => {
                setStep(1);
                setCodeId('');
                setToAccount('');
                setAmount('');
                setNarration('');
              }}
              className="py-2 px-6 bg-gray-900 text-white rounded font-medium"
            >
              Start New Transfer
            </button>
          </div>
        )}
      </div>
    </div>
  );
};

export default InitiateTransfer;
